// <auto-generated />
using System;
using Intex313.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Intex313.Migrations
{
    [DbContext(typeof(AccidentDbContext))]
    [Migration("20220405052351_ebdb")]
    partial class ebdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Intex313.Models.Accident", b =>
                {
                    b.Property<int>("Crash_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool?>("Bicyclist_Involved")
                        .HasColumnType("boolean");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<bool?>("Commercial_Motor_Veh_Involved")
                        .HasColumnType("boolean");

                    b.Property<string>("County_Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Crash_Date_Time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Crash_Severity_ID")
                        .HasColumnType("integer")
                        .HasMaxLength(1);

                    b.Property<bool?>("DUI")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Distracted_Driving")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Domestic_Animal_Related")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Drowsy_Driving")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Improper_Restraint")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Intersection_Related")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Lat_Utm_Y")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Long_Utm_Y")
                        .HasColumnType("numeric");

                    b.Property<string>("Main_Road_Name")
                        .HasColumnType("character varying(150)")
                        .HasMaxLength(150);

                    b.Property<decimal?>("MilePoint")
                        .HasColumnType("numeric");

                    b.Property<bool?>("Motorcycle_Involved")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Night_Dark_Condition")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Older_Driver_Involved")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Overturn_Rollover")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Pedestrian_Involved")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Roadway_Departure")
                        .HasColumnType("boolean");

                    b.Property<string>("Route")
                        .HasColumnType("text");

                    b.Property<bool?>("Single_Vehicle")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Teenage_Driver_Involved")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Unrestrained")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Wild_Animal_Related")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Work_Zone_Related")
                        .HasColumnType("boolean");

                    b.HasKey("Crash_ID");

                    b.ToTable("Accidents");
                });
#pragma warning restore 612, 618
        }
    }
}
